version: 2.1
orbs:
  heroku: circleci/heroku@1.0.1
executors:
  node:
    docker:
      - image: circleci/node:10
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build
          filters:
            branches:
              only: master
jobs:
  build:
    executor: node
    steps:
      - checkout
      - run: npm install
      - run: npm run build
