name: Docker Image CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag twitscrapeapi_latest:$(date +%s)

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: twitscrapeapi_latest
        # A file, directory or wildcard pattern that describes what to upload
        path: .
